

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/securitygetarray?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true